---
# - name: Configure application servers
#  hosts: tag_Role_private_app
#  become: true

#  roles:
#    - node_exporter

# - name: Configure Prometheus
#  hosts: tag_Role_prometheus
#  become: true

#  roles:
#    - prometheus

# - name: Configure Grafana
#  hosts: tag_Role_grafana
#  become: true

#  roles:
#    - grafana

- name: Verify connectivity playbook
  import_playbook: verify_connectivity.yaml

- name: Configure router playbook
  import_playbook: configure_router.yaml

- name: Install observability playbook
  import_playbook: install_observability.yaml
