---
- name: Configure application servers
  hosts: ip-address
  become: true

  roles:
    - node_exporter

- name: Configure Prometheus
  hosts: prometheus
  become: true

  roles:
    - prometheus

- name: Configure Grafana
  hosts: grafana
  become: true

  roles:
    - grafana
- name: Verify connectivity playbook
  import_playbook: verify_connectivity.yaml

- name: Configure router playbook
  import_playbook: configure_router.yaml

- name: Install observability playbook
  import_playbook: install_observability.yaml
