---
- name: Install Docker and Python Docker SDK
  ansible.builtin.dnf:
    name:
      - docker
      - python3-docker
    state: present

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Create prometheus config directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: "0755"

- name: Write prometheus.yaml
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yaml
    mode: "0644"
  notify: Restart Prometheus

- name: Run prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart_policy: always
    ports:
      - 9090:9090
    volumes:
      - /etc/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro,z
