- name: Enable BGP process
  cisco.ios.ios_config:
    parents:
      - "router bgp {{ bgp_as }}"
    lines:
      - "bgp router-id {{ router-id }}"
      - "bgp log-neighbor-changes"

- name: COnfigure BGP neighbors
  cisco.ios.ios_config:
    parents:
      - "router bgp {{ bgp_as }}"
    lines:
      - "neighbor {{ item.ip }} remote-as {{ item.remote-as }}"
  loop: "{{ neighbors }}"

- name: Advertise networks
  cisco.ios.ios_config:
    parents:
      - "router bgp {{ bgp_as }}"
    lines:
      - "network {{ item }}"
  loop: "{{ networks }}"

