
---
all:
  children:
    tag_Role_bastion:tag_Role_private_app:
      hosts:
        bastion_staging:
          ansible_host: 3.235.17.40 
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/capstonekey.pem
          ansible_python_interpreter: /usr/local/bin/python3.11

    tag_Role_prometheus:
      hosts:
        prometheus_staging:
          ansible_host: 10.1.2.237
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/capstonekey.pem
          ansible_python_interpreter: /usr/local/bin/python3.11
          ansible_ssh_common_args: >-
            -o ProxyJump=ec2-user@3.235.17.40

    tag_Role_grafana:
      hosts:
        grafana_staging:
          ansible_host: 3.85.228.141
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/capstonekey.pem
          ansible_python_interpreter: /usr/local/bin/python3.11
    
    tag_Role_router:
      hosts:
        router_staging:
          ansible_host: 54.83.75.12
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/capstonekey.pem
          ansible_python_interpreter: /usr/local/bin/python3.11
    
