# I believe this is where we're supposed to put the hosts that we actually want to connect to for production
---
all:
  children:
    app_servers:
      hosts:
        app_staging_1:
          ansible_host: 34.205.85.247 #Whichever one we're connecting to, Terraform people might know
          ansible_user: platform-capstone-bastion #ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa